<script type="text/javascript">
// <![CDATA[
(function ($) {
    $(document).ready(function () {
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    var data = $(form).serialize();
                    $.ajax('<?php echo $this->getUrl('jbh_ajaxcart/index/add'); ?>', {
                        type: 'POST',
                        data: data,
                        success: function (data, textStatus, jqXHR) {
                            alert(data);
                        },
                        error: function (jqXHR, textStatus, errorThrown) {
                            button.disabled = false;
                        },
                        dataType: 'html'
                    });
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);
    });
})(jQuery);
// ]]>
</script>